//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myFirstApp_mobile_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mobile
    {
        public int mobile_id { get; set; }
        public string mobile_name { get; set; }
        public int mobile_price { get; set; }
        public string mobile_model { get; set; }
        public int brand_id { get; set; }
    
        public virtual brand brand { get; set; }
    }
}
