//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
namespace myFirstApp_mobile_.Models
{
    
    
    public partial class userRegistration
    {
        public int user_id { get; set; }
        [Display(Name ="First Name")]
        [Required(ErrorMessage ="First name is required")]
        public string firstName { get; set; }
        [Display(Name = "Last Name")]
        [Required(ErrorMessage = "Last name is required")]
        public string lastName { get; set; }
        [Display(Name = "Email Address")]
        [Required(ErrorMessage = "Email Address is required")]
        public string emailAddress { get; set; }
        [Display(Name = "Phone No")]
        [Required(ErrorMessage = "Phone No is required")]
        public int phoneNo { get; set; }
        [Display(Name = "Password")]
        [Required(ErrorMessage = "Password is required")]
        public string password { get; set; }
    }
}
